### ISSUE TITLE
Cannot find symbol `replaceValue`

### ISSUE THREAD

**Issue by andrewbaxter439** [centreformicrosimulation/SimPaths#19]
https://github.com/centreformicrosimulation/SimPaths/blob/e9e3980d18313c3090947e01aeaadbf1cac7b361/src/main/java/simpaths/data/Parameters.java#L2519C15-L2519C15

Should this be `valueMap.replace(year, valPut);`?

At the moment returns `[ERROR]  cannot find symbol; symbol:   method replaceValue(int,java.lang.Object)` on compilation

**Comment by andrewbaxter439** [comment]
@justin-ven apologies was playing around with this and not sure if it's an error?

**Comment by pbronka** [comment]
replaceValue requires JAS-mine-core version 4.3.4 or higher. I have updated the pom.xml of SimPaths which should fix this so closing.
