### ISSUE TITLE
Static `this.startYear = 2016` overriding `startYear` argument

### ISSUE THREAD

**Issue by andrewbaxter439** [centreformicrosimulation/SimPaths#30]
Introduced in ecf7432b885912b623a0cc5c552ff75bee2adc52 - presume this is perhaps a step in that validation process but thought worth highlighting in case needs reversed.

https://github.com/centreformicrosimulation/SimPaths/blob/e29c5297ad64e5be5f8de15b24006467b05ff3cc/src/main/java/simpaths/model/SimPathsModel.java#L290-L291

**Comment by andrewbaxter439** [comment]
Sorry @justin-ven @pbronka - had meant to highlight this in email in case causes problems?

**Comment by pbronka** [comment]
I don't think this should have made its way onto GitHub but will wait for @justin-ven to comment. 

Good news is that it was merged in recently (https://github.com/centreformicrosimulation/SimPaths/pull/29)

**Comment by justin-ven** [comment]
Looks wrong to me - apologies if I was responsible for it!

**Comment by pbronka** [comment]
Fixed (https://github.com/centreformicrosimulation/SimPaths/pull/35) so closing, thanks @andrewbaxter439 for spotting this!
