### ISSUE TITLE
`multiRunId` set to '0' for all runs

### ISSUE THREAD

**Issue by andrewbaxter439** [centreformicrosimulation/SimPaths#64]
Hi @justin-ven - noticed that when I was running new multiruns it seems to set the folder to always end in '_0', where it used to put the random seed at the end. This was accomplished in JAS-mine by naming the folder with `outputRootFolder + File.separatorChar + runId + "_" + multiRunId;`

But the amended line below sets the multirun ID to the run counter, thus naming the folder with a zero at the start of the run:

https://github.com/centreformicrosimulation/SimPaths/blob/94bd8baff4dc4ddc2c3612ff2ea9e818d11a6a99/src/main/java/simpaths/experiment/SimPathsMultiRun.java#L404-L406

(changed from `randomSeed.toString()` in 6b30b12c834b93b887f50c5c736d65ae12165013).

Is there a possibility of combining both, and making the `setupRunLabel` function concatenate `randomSeed.toString() + "_" + counter.toString()`? I'd propose this primarily as a way of distinguishing two runs started with separate seeds - I'd added the random seed to the output folder name to stop parallel runs from interfering. Does anything significant depend on the run ID being precisely the counter as a string?

Thanks for insight on this.

**Comment by justin-ven** [comment]
Hi @andrewbaxter439 - very happy for the folder to be renamed as you suggest.  Nothing depends on the run id (I can't recall now why I altered it).

**Comment by andrewbaxter439** [comment]
will see about fixing it with a quick pull request
